### ISSUE TITLE
How to inspect wrong validation predictions during training?

### ISSUE THREAD

**Issue by ani-mal** [Deci-AI/super-gradients#1817]
### Description 

I am training a model and I am logging the validation predictions. However, I would like to change the implementation to only log the wrong predictions, so I can inspect the failure cases as opposed to the top results. 

here is how I am logging the predictions:

```python
@register_callback()
class MLFlowEpochEndCallback(Callback):
        def __init__(self, post_prediction_callback, classes, predict_epoch_frequency=10, predict_sample_freq=10 ):
            self.post_prediction_callback = post_prediction_callback
            self.classes =classes 
            self.predict_epoch_frequency = predict_epoch_frequency
            self.predict_sample_freq = predict_sample_freq

...
@multi_process_safe
        def on_validation_batch_end(self, context: PhaseContext) -> None:
            if (context.epoch % self.predict_epoch_frequency)==0  and (context.batch_idx % self.predict_sample_freq) == 0:
              image back into its initial formal (BGR, uint8)
                def my_undo_image_preprocessing(inputs: torch.Tensor) -> np.ndarray:
                    inputs -= inputs.min()
                    inputs /= inputs.max() + 1e-8
                    inputs *= 255
                    inputs = inputs.to(torch.uint8)
                    inputs = inputs.cpu().numpy()
                    inputs = inputs[:, ::-1, :, :].transpose(0, 2, 3, 1)
                    inputs = np.ascontiguousarray(inputs, dtype=np.uint8)
                    return inputs

                predictions_dirname = f'{context.sg_logger._local_dir}/predictions'
                os.makedirs(predictions_dirname, exist_ok=True)
                
                preds = self.post_prediction_callback(context.preds)
                batch_imgs = DetectionVisualization.visualize_batch(context.inputs, preds, context.target, context.epoch, self.classes, gt_alpha=0.0, undo_preprocessing_func=my_undo_image_preprocessing)
              
                batch_imgs = np.stack(batch_imgs)
                for i, img in enumerate(batch_imgs):
                    img = cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA)
                    cv2.imwrite(f'{predictions_dirname}/batch_image_epoch{context.epoch}_batch_id{context.batch_idx}.png', img)
```

and the post prediction callback is the following:

```
  phase_callbacks:
      - MLFlowEpochEndCallback:
          post_prediction_callback:
            _target_: super_gradients.training.models.detection_models.pp_yolo_e.PPYoloEPostPredictionCallback
            score_threshold: 0.50
            nms_top_k: 1000
            max_predictions: 300
            nms_threshold: 0.7
          classes: ${classes_list}
          predict_sample_freq: 1
          predict_epoch_frequency: 1
```

So the predictions I am getting are just the best predictions that are being filtered based on the `phase_callbacks`. I want to minimize the number of artifacts that are being generated during validation, and just log the cases where all predictions are bad ( based on a threshold, like don't log the samples where all grand truth objects were detected with a confidence of > 0.5 ), I just want to inspect the cases where the detection is not finding any Grand Truth. It seems to me I would need to implement a custom `post_prediction_callback` or is there something like that already implemented on SG? If there isn't, do you have documentation or an example of how I can implement my own `post_prediction_callback`?
